### ISSUE TITLE
Issues installing Alexa skill.

### ISSUE THREAD

**Issue by johnenright** [koush/scrypted.app#3]
I'm getting: "We were unable to link Scrypted Home Automation at this time." after successfully logging in to scrypted cloud. Have tried from several devices and browsers. home.scrypted.app works fine when logging in directly from a browser on any of the same devices.

I should add: thanks creating for this awesome framework!!

**Comment by koush** [comment]
Is the Alexa plugin installed?

**Comment by koush** [comment]
Please join discord and use the Alexa channel, this Github is for issue tracking, not support.
